smartapp-developers-guide/index.rst
smartapp-developers-guide/scheduling.rst

need to add time-related APIs/information as well.

add scheduling section to SmartApp developer's guide.

---

smartapp-developers-guide/scheduling.rst

@mrnohr should review this before merging.

add documentation around runEveryXMinutes/hours to scheduling topic.

---

smartapp-developers-guide/index.rst
smartapp-developers-guide/sunset-and-sunrise.rst

Added a section to the SmartApp Developer's Guide for Sunset and Sunrise. Also linked to some examples in the new Code repo in the SmartThingsCommunity project (we will want to more broadly publicize this at some point in the near future).
@mrnohr you should verify that the content is correct. @mager this is an example of linking to the examples from our guides.

add sunrise and sunset documentation

---

arduino/index.rst
index.rst

See https://smartthings.atlassian.net/browse/DEVP-11

Adding Arduino documentation from support.smartthings.com [DEVP-11]

---

smartapp-developers-guide/calling-web-services-in-smartapps.rst

@mager this might be good for you to review.

update calling web services guide.

---

introduction/groovy-the-smartthings-programming-language.rst

http://learnxinyminutes.com/docs/groovy/

Added a link to a five minute Groovy tutorial

---

device-type-developers-guide/index.rst
device-type-developers-guide/submitting-device-types-for-publication.rst

Hey Jim, please give this a read and publish at your convenience. We will do the same for SmartApps soon.

New section: Device Type Submission Guidelines

---

device-type-developers-guide/definition-metadata.rst
device-type-developers-guide/overview.rst
smartapp-developers-guide/devices.rst
smartapp-developers-guide/preferences-and-settings.rst
smartapp-developers-guide/scheduling.rst

minor grammar and spelling fixes found when reviewing docs.

fixing some minor issues in the docs

---

smartapp-developers-guide/preferences-and-settings.rst

adding additional mode documentation, input enum data type vs. mode method

adding additional mode documentation

---

capabilities-reference.rst

adding some clarifications to colorControl

adding some clarifications to colorControl

---

capabilities-reference.rst

momentary and motion sensor examples

capabilities

---

smartapp-developers-guide/calling-web-services-in-smartapps.rst

add more info around calling web services.

---

device-type-developers-guide/submitting-device-types-for-publication.rst
smartapp-developers-guide/submitting-smartapps-for-publication.rst

We wanted to improve the docs to give users more insight into the approval process.

Updated SmartApp Publication Guidelines with @kris-schaller and Dwight

---

ref-docs/smartapp-ref.rst
smartapp-developers-guide/index.rst
smartapp-developers-guide/sending-notifications.rst

This is fairly straightforward; just adding some docs around sending notifications in SmartApps.
/cc @mrnohr @unixbeast

add guide for sending notifications.

---

ref-docs/smartapp-ref.rst
smartapp-developers-guide/sending-notifications.rst

Adding information about other notification APIs, `sendNotification()` and `sendNotificationEvent()`.
/cc @mrnohr @unixbeast

Add info about sendNotification and sendNotificationEvent

---

capabilities-reference.rst
conf.py

just some minor tweaks to get PDF generation working (sort of), at least locally.
There's still a character encoding problem that prevents the PDF from being generated on RTD. When time allows, we can look into that too...

Fix tables

---

smartapp-developers-guide/preferences-and-settings.rst

new documentation around the submitOnChange attribute for input. For dynamic pages.

Submit on change

---

smartapp-web-services-developers-guide/tutorial-part2.rst

/cc @beckje01, @llinder, @unixbeast fyi. 
There's some formatting diffs included here you can ignore - content changes starts towards the bottom at "Get the API token" section heading.

update docs with OAuth changes that impact getting the access token.

---

device-type-developers-guide/definition-metadata.rst

Updating the documentation around fingerprinting with information about adding manufacturer name and model, as well as certain best practices as identified by engineering.
@workingmonk you should review this entire fingerprinting section to make sure it is accurate and complete.

update fingerprinting docs with manufacturer info and best practices.

---

ref-docs/device-handler-ref.rst

updating device handler ref with correct attribute signature

updating device handler ref with correct attribute signature

---

ref-docs/device-handler-ref.rst

updating device handler ref with correct attribute signature

one more minor adjustment for attribute api

---

ref-docs/device-handler-ref.rst
ref-docs/smartapp-ref.rst

This adds some reference docs for getting the API server URLs.
/cc @kyleboon can you take a quick look?

Add reference docs for getting the API server URLs.

---

ref-docs/location-ref.rst

adding docs for getting the temperature scale for a location.

add docs for getting the temperatureScale for a location.

---

ref-docs/device-handler-ref.rst

HTTPGet was referencing HTTP DELETE not GET

Fixed HTTP Get error

---

ref-docs/device-ref.rst
ref-docs/hub-ref.rst
ref-docs/location-ref.rst
ref-docs/reference.rst

Added reference documentation for the Hub object.

Add reference documentation for the Hub object.

---

smartapp-developers-guide/preferences-and-settings.rst

Docs PR 171 included a few corrections to the preferences guide. Because we refactored the introduction section, some of the other changes in that PR are addressed separately.
This PR fixes other issues in PR 171 as found by @mrobinet

fix errors found in PR 171

---

smartapp-developers-guide/preferences-and-settings.rst

yet another typo

---

cloud-and-lan-connected-device-types-developers-guide/building-lan-connected-device-types/building-the-service-manager.rst

fixed missing closing brackets in a code example as found by a community member (leeOjones).

Fix code example bug as found by leeOjones.

---

smartapp-web-services-developers-guide/tutorial-part2.rst

updating web services smartapp example to use the URI parameter

updating web services smartapp example to use the URI parameter

---

smartapp-developers-guide/preferences-and-settings.rst

rst tables are finicky. Recent typo fix caused inputs table to not render.

fix table formatting issue introduced in PR 197

---

device-type-developers-guide/tiles-metadata.rst

adding warning about multiAttributeTiles on Android

adding warning about multiAttributeTiles on Android

---

capabilities-reference.rst

New capabilities

---

smartapp-web-services-developers-guide/smartapp.rst

add documentation for using oauthPage option for web services preferences.

oauthPage preferences

---

device-type-developers-guide/building-zigbee-device-handlers.rst
device-type-developers-guide/zigbee-primer.rst
ref-docs/reference.rst
ref-docs/zigbee-ref.rst

@workingmonk @tpmanley @jimmyjames 
Please review and let me know whether or not you would like me to make changes to this starting point for the zigbee utility stuff.

Initial Documentation commit of new zigbee utility class

---

device-type-developers-guide/building-zigbee-device-handlers.rst

This documents the new ZigBee device handler form. 
A larger effort to reorganize and expand upon the different ways device handlers can be created is planned for the future.

DOCS-198 - document the new zigbee device handler form.

---

device-type-developers-guide/building-zigbee-device-handlers.rst

This reverts commit ffc97b4dcdeebed7c688ea44f78dfb6e95975db3.
ZigBee Device form is not yet enabled.

Revert "DOCS-198 - document the new zigbee device handler form."

---

capabilities-reference.rst

Document the Color Temperature Capability

Color temp capability

---

capabilities-reference.rst

Show executing commands as well as subscribing to state changes for the Lock capability.

clarify the lock capability SmartApp example.

---

common/oauth-install-restriction.rst
smartapp-web-services-developers-guide/authorization.rst
smartapp-web-services-developers-guide/tutorial-part2.rst

Document the restriction that only approved SmartApps may be installed via the OAuth flow.

DOCS-218 - OAuth install restriction.

---

device-type-developers-guide/building-zigbee-device-handlers.rst

Supporting documentation for the new ZigBee form creation option.

DOCS-198 - Update ZigBee docs to include the new ZigBee form creation.

---

smartapp-web-services-developers-guide/authorization.rst

removing GET as a method option for getting access token

DOCS-224: removing GET as a method option for getting access token

---

smartapp-developers-guide/state.rst

The amount of data that can be stored in state or atomicState is currently limited to 100K characters. This PR documents that limitation.
I also added a Best Practices section that summarizes some of important information to keep in mind when using state.
@rappleg I think you should check this for accuracy before it's merged.

Document state character size limitation (DOCS-211)

---

ref-docs/hub-ref.rst

Looks like there was some out of control copy/paste :)

Correct description of Hub#localIp

---

capabilities-reference.rst

@Yaima since you added these capabilities, would like your review before merging. Thanks!
/cc @jodyalbritton

DOCS-249 - add new capabilities to docs

---

smartapp-developers-guide/scheduling.rst

Adding note to cron expression for 1 minute interval limit

---

smartapp-developers-guide/preferences-and-settings.rst

internal bug for issue has been created.

issue #261 - images do not render for label elements.

---

getting-started/groovy-basics.rst
getting-started/groovy-for-smartthings.rst

Seen this before, and there was some chatter over in the community slack around how to create global variables in a SA/DT. Some apps are defining global constants, which compile fine, but are always `null`.
This PR attempts to clarify how to create a "global" constant.
@mrnohr maybe you can review if not we can bother a cloud dev

global variables seem like they should work, but don't

---

smartapp-web-services-developers-guide/smartapp.rst

This PR adds some information around the default responses sent back for the various request methods, as well as errors that may be thrown by the platform.
@rappleg you or someone of your delegating should review to ensure this is consistent with your expectations, and also so you are aware should you want/plan on changing anything.
/cc @mrnohr

DOCS-274 enumerate default response/error conditions for web service handlers

---

smartapp-web-services-developers-guide/authorization.rst
smartapp-web-services-developers-guide/index.rst
smartapp-web-services-developers-guide/overview.rst
smartapp-web-services-developers-guide/rate-limiting.rst
smartapp-web-services-developers-guide/smartapp.rst
smartapp-web-services-developers-guide/tutorial-part1.rst
smartapp-web-services-developers-guide/tutorial-part2.rst

Also reordered structure so the tutorials come before the other documentation.
@unixbeast

formatting web services guide

---

ref-docs/smartapp-ref.rst
smartapp-developers-guide/anatomy-and-life-cycle-of-a-smartapp.rst
smartapp-developers-guide/app-touch.rst
smartapp-developers-guide/calling-web-services-in-smartapps.rst
smartapp-developers-guide/devices.rst
smartapp-developers-guide/example-bon-voyage.rst
smartapp-developers-guide/index.rst
smartapp-developers-guide/modes.rst
smartapp-developers-guide/parent-child-smartapps.rst
smartapp-developers-guide/preferences-and-settings.rst
smartapp-developers-guide/routines.rst
smartapp-developers-guide/scheduling.rst
smartapp-developers-guide/sending-notifications.rst
smartapp-developers-guide/simple-event-handler-smartapps.rst
smartapp-developers-guide/state.rst
smartapp-developers-guide/submitting-smartapps-for-publication.rst
smartapp-developers-guide/sunset-and-sunrise.rst

formatting fixes for SmartApp guide

---

getting-started/first-smartapp.rst
getting-started/getting-help.rst
getting-started/groovy-basics.rst
getting-started/groovy-for-smartthings.rst
getting-started/overview.rst
getting-started/up-and-running.rst

formatting cleanup of getting started material

---

device-type-developers-guide/building-z-wave-device-handlers.rst
device-type-developers-guide/building-zigbee-device-handlers.rst
device-type-developers-guide/definition-metadata.rst
device-type-developers-guide/device-integration.rst
device-type-developers-guide/device-preferences.rst
device-type-developers-guide/index.rst
device-type-developers-guide/overview.rst
device-type-developers-guide/parse.rst
device-type-developers-guide/quick-start.rst
device-type-developers-guide/simulator-metadata.rst
device-type-developers-guide/standard-device-type-pattern.rst
device-type-developers-guide/submitting-device-types-for-publication.rst
device-type-developers-guide/tiles-metadata.rst
device-type-developers-guide/z-wave-primer.rst
device-type-developers-guide/zigbee-primer.rst

formatting for device handler guide

---

capabilities-reference.rst
ref-docs/attribute-ref.rst
ref-docs/capability-ref.rst

formatting for capabilities ref and a couple other missed reference docs

---

tools-and-ide/account-mgmt.rst
tools-and-ide/editor-and-simulator.rst
tools-and-ide/github-integration.rst
tools-and-ide/index.rst
tools-and-ide/logging.rst

format tools and IDE guide

---

ref-docs/command-ref.rst
ref-docs/device-handler-ref.rst
ref-docs/device-ref.rst
ref-docs/event-ref.rst
ref-docs/hub-ref.rst
ref-docs/location-ref.rst
ref-docs/mode-ref.rst
ref-docs/reference.rst
ref-docs/state-ref.rst
ref-docs/zigbee-ref.rst

reference docs formatting

---

README.md
smartapp-web-services-developers-guide/overview.rst

also added a fix for a separator here, since I noticed it.
@unixbeast

add style guide link to README

---

device-type-developers-guide/definition-metadata.rst
device-type-developers-guide/zigbee-primer.rst

Resolves:
https://smartthings.atlassian.net/browse/DOCS-276

Documented the new single-phase ZigBee device discovery process

---

architecture/index.rst
contributing/style-guide.rst
getting-started/first-smartapp.rst
getting-started/groovy-basics.rst
smartapp-developers-guide/calling-web-services-in-smartapps.rst
smartapp-developers-guide/example-bon-voyage.rst
smartapp-developers-guide/preferences-and-settings.rst
smartapp-developers-guide/scheduling.rst
smartapp-developers-guide/sending-notifications.rst
smartapp-web-services-developers-guide/overview.rst

These are mostly minor changes, but are not thorough, in that they are what I stumbled across in my first perusal of this documentation. Overall I've seen inconsistency in things like periods at the end of sentences (especially in lists), use of ampersands instead of "and" and use of hyphens instead of real dashes, colons, etc. I've opened a few issues since I didn't want to take it upon myself to make too many changes.

Corrections and style fixes

---

capabilities-reference.rst

While internal discussion around this command is ongoing, I at least want to provide _some_ level of clarification in the docs until it's all sorted out.

setLevel clarification

---

tools-and-ide/cli.rst

And I wanted to play in the secret playground too.

Minor typo Wed vs Web

---

getting-started/getting-help.rst

[DOCS-301] Document new support form

---

smartapp-developers-guide/preferences-and-settings.rst

/cc @tslagle13 @mrnohr 
Going to merge this since it's been reviewed offline.

[DOCS-305] document how device-specific preference inputs work

---

getting-started/getting-help.rst

@unixbeast please take a quick look.
/cc @tslagle13

[DOCS-301] Formatting changes for the new developer support form

---

cloud-and-lan-connected-device-types-developers-guide/building-lan-connected-device-types/building-the-service-manager.rst
code-review-guidelines.rst
device-type-developers-guide/submitting-device-types-for-publication.rst
docs-change-log.rst
index.rst
smartapp-developers-guide/scheduling.rst
smartapp-developers-guide/sending-notifications.rst
smartapp-developers-guide/state.rst
smartapp-developers-guide/submitting-smartapps-for-publication.rst

The release has the new guidelines and best practices docs.

Release 13 june 2016

---

cloud-and-lan-connected-device-types-developers-guide/building-lan-connected-device-types/building-the-device-type.rst

Adding wake on lan HubAction documentation

DOCS-196 Adding WOL HubAction documentation

---

cloud-and-lan-connected-device-types-developers-guide/building-lan-connected-device-types/building-the-device-type.rst
docs-change-log.rst

Release 17 june 2016

---

capabilities-reference.rst

breaking out music player capability into 3 capabilities:
* audio notification
* music player
* tracking music player

DOCS-310 breaking out music player capability

---

ref-docs/app-state-ref.rst
ref-docs/app-state.rst
ref-docs/installed-smart-app-wrapper-ref.rst
ref-docs/reference.rst
ref-docs/smartapp-ref.rst
smartapp-developers-guide/parent-child-smartapps.rst
smartapp-developers-guide/preferences-and-settings.rst

initial commit of InstalledSmartAppWrapper
adding new installedSmartAppWrapper document in reference material
adding class links
commit of InstalledSmartAppWrapper and AppState documentation

DOCS-204 documenting SmartApp meta object

---

smartapp-developers-guide/state.rst

[DOCS-318] yell loudly about not mixing state and atomicState

---

ref-docs/zigbee-ref.rst

@tpmanley @workingmonk @jimmyjames

Add documentation for ZigBee ZoneStatus

---

ref-docs/app-state-ref.rst
ref-docs/event-ref.rst
tools-and-ide/logging.rst

@vl4ds please review. Once it has a thumbs-up, I will merge this and publish the updated docs when this hits prod.

[DOCS-317] update docs with new logger method that accepts a Throwable

---

.gitignore
_static/capabilities/color-control.src/color-control.xml
_static/capabilities/color-control.src/colorControl.properties
_static/capabilities/music-player.src/music-player.xml
_static/capabilities/music-player.src/musicPlayer.properties
_static/capabilities/switch.src/switch.properties
_static/capabilities/switch.src/switch.xml
docs-change-log.rst
ref-docs/app-state-ref.rst
ref-docs/event-ref.rst
tools-and-ide/logging.rst

docs release for august 16 2016

Docs release

---

tools-and-ide/account-mgmt.rst

Fix a typo

---

smartapp-web-services-developers-guide/index.rst
smartapp-web-services-developers-guide/troubleshooting.rst

We probably should have had some troubleshooting docs for OAuth SmartApps for a while, and I think there's more that can be added here. But there are some topics I think we can address to start, that will be helpful for developers who get stuck in common areas.
@llinder would like your review of this before merging.
/cc @unixbeast @tslagle13

[DOCS-324] Start of troubleshooting docs for OAuth SmartApps

---

conf.py
requirements.txt
test.rst

Adding ability to consume the capability XML and property files in the Docs build.

DOCS-327 Adding ability to consume the capability files

---

conf.py
docs-change-log.rst

Release 02 september 2016 02

---

device-type-developers-guide/building-z-wave-device-handlers.rst
device-type-developers-guide/z-wave-primer.rst
ref-docs/z-wave-ref.rst

@mckeed nothing to earth-shattering here just adding links to the Z-Wave public spec.

[DOCS-340] link to Z-Wave public specification

---

code-review-guidelines.rst

@jimmyjames Can you take a look at this?

simple spelling fix

---

device-type-developers-guide/other-available-apis.rst
ref-docs/device-handler-ref.rst
ref-docs/smartapp-ref.rst
smartapp-developers-guide/scheduling.rst

also added all scheduling methods to device handler reference docs

[DOCS-343] - runEveryXMinutes/hours being added to device executor base

---

getting-started/getting-help.rst

@tslagle13 take a look at this and see if it's clear.
/cc @rajkaramchedu

[DOCS-350] creating a good dev support ticket

---

docs-change-log.rst
smartapp-developers-guide/scheduling.rst

This fixes the change log for yesterday's release

merging master into release

---

architecture/index.rst

@jimmyjames Can you please take a look at this hyphenation fix I am proposing? Thanks!

Single instance hyphenation fix

---

architecture/index.rst

@jimmyjames Please check and approve this spello fix. Thanks!

Single spelling fix

---

Makefile
_static/capabilities/color-control.src/color-control.xml
_static/capabilities/color-control.src/colorControl.properties
_static/capabilities/music-player.src/music-player.xml
_static/capabilities/music-player.src/musicPlayer.properties
_static/capabilities/switch.src/switch.properties
_static/capabilities/switch.src/switch.xml
test.rst

committing latest XML and property file changes.
also updating the jinja template to reflect those changes.

DOCS-356 updating XML files and the jinja template

---

smartapp-developers-guide/sending-notifications.rst

@lbredeso you should review this.
/cc @rajkaramchedu after this is merged you'll want to add this to the things we'll want to pull out into separate Rate Limiting documentation.

[DOCS-355] document SMS rate limiting

---

smartapp-developers-guide/anatomy-and-life-cycle-of-a-smartapp.rst

@jimmyjames these minor edits are in more than one place, and all edits are sentence rewording.

[DOCS-363, DOCS-345] Minor edits: sentence rewording

---

capabilities-reference.rst

[DOCS-367] - add additional lock attribute values

---

ref-docs/installed-smart-app-wrapper-ref.rst
ref-docs/smartapp-ref.rst

@tslagle13 @chrisfsmith this adds some example code and links for getting the installation state of a child SmartApp install.

[DOCS-344] clarify getting installation state for child smartapp

---

ref-docs/smartapp-ref.rst

Revised timeTodayAfter() description.

Revised timeTodayAfter() method description

---

ref-docs/smartapp-ref.rst
smartapp-developers-guide/index.rst
smartapp-developers-guide/time-methods.rst

First draft of documenting executing within a time window. At least two more revisions will be made to this doc: (1) Illustrating the default time zone setting and (2) revising the time window logic table.

[DOCS-369] Documenting time window use case

---

ref-docs/device-ref.rst
smartapp-developers-guide/devices.rst

@jasonbio @jackchi can you see if this helps to clarify?
@rajkaramchedu would be good for you to review as well since you have a fresh perspective.

[DOCS-372] clarify getting latest device state

---

smartapp-developers-guide/time-methods.rst

This use case, execute on preferred days of week, does not introduce any new time-related API. Still the use case is valid to illustrate working with time. I'll think on coming up with a case that introduces one to two new time-related methods.

[DOCS-371] Adding usecase of executing on certain days-of-week

---

test.rst

Noticed I had to update the template to support required arguments.
Also getting rid of some unnecessary legacy garbage at the end of the template.
@jimmyjames @rajkaramchedu

DOCS-374 update template

---

smartapp-developers-guide/state.rst

I've just fixed few code blocks.

Update state page

---

test.rst

updated the template for the case where there is only one command that has attributes.

DOCS-376 updating template to correct missing content

---

cloud-and-lan-connected-device-types-developers-guide/building-lan-connected-device-types/building-the-service-manager.rst
code-review-guidelines.rst
contributing/style-guide.rst
device-type-developers-guide/tiles-metadata.rst
ref-docs/attribute-ref.rst
ref-docs/device-handler-ref.rst
smartapp-developers-guide/async-http.rst
smartapp-developers-guide/preferences-and-settings.rst
tools-and-ide/logging.rst

Fixing lex warnings

---

docs-change-log.rst
smartapp-developers-guide/time-methods.rst

Also includes a fix for broken ref target link, and whitespace cleanup

release notes for 14 November 2016 release

---

test.rst

DOCS-380 noticed incorrect indentation and fixed it

---

test.rst

@jimmyjames @rajkaramchedu 
this was another case where I just copied how attributes were displayed from above in the file.

DOCS-381 fixing displayed attribute if there is only one

---

_static/css/custom.css
_static/javascript/copycode.js

better alignment for the copy button, move tooltip to out of the code block

copy code block style changes

---

_static/css/custom.css
_templates/layout.html
conf.py
getting-started/groovy-basics.rst
smartapp-web-services-developers-guide/smartapp.rst

Use the monokai code highlighting theme. 
Also made a few changes to code blocks that were not rendering properly.
Reviewed offline with @unixbeast

dark code block theme

---

test.rst

DOCS-385 adding support for command argument values to template

---

smartapp-developers-guide/preferences-and-settings.rst

@vlaminck @tpmanley Please review, thanks.

[DOCS-247] Added dynamicPage() params description

---

test.rst

DOCS-386 fixing spacing/newline issues in template

---

test.rst

DOCS-387 adding a missing label

---

test.rst

DOCS-402 adding support for optional attributes

---

conf.py

Release 01 december 2016 02

---

ref-docs/smartapp-ref.rst

must have fallen on the space bar there....

fix typo in httpPostJson docs

---

test.rst

DOCS-416 adding data type descriptions

---

architecture/index.rst

This is a clean version of PR #507 with only a single commit. After this is merged I will close PR #507  https://github.com/SmartThingsCommunity/Documentation/pull/507

[DOCS-347] Added Hubs and Locations Section

---

smartapp-developers-guide/scheduling.rst

Elaborated cron-specific sections highlighted in community here: https://community.smartthings.com/t/announcement-changes-coming-to-cron-jobs/41656/20
Also edited other sections of the document for better readability.
@tslagle13 like to get your eyes on this, please. Thanks!

[DOCS-368] Cron schedule elaboration and other readability edits

---

getting-started/groovy-basics.rst

fix grammar error

---

arduino/index.rst

Fix for issue #536 
@rajkaramchedu

deprecate arduino docs

---

cloud-and-lan-connected-device-types-developers-guide/building-lan-connected-device-types/building-the-device-type.rst
smartapp-developers-guide/calling-web-services-in-smartapps.rst

The spelling of the word "request" was fixed.

[DOCS-439] Fixed spello for word "request"

---

ref-docs/installed-smart-app-wrapper-ref.rst

[DOCS-441] add getAccountId to IntalledSmartAppWrapper ref doc

---

architecture/index.rst
index.rst
latest-updates.rst
smartapp-developers-guide/preferences-and-settings.rst
smartapp-developers-guide/scheduling.rst

@jimmyjames See what you think of this approach? The intent is this: the "What's New" page will only focus on last changes, highlighting their benefits with a short blurb, and the docs change log is right below it for those who want to delve into details and for some history.

[DOCS-426] Adding Whats New Section

---

cloud-and-lan-connected-device-types-developers-guide/building-lan-connected-device-types/building-the-device-type.rst
cloud-and-lan-connected-device-types-developers-guide/building-lan-connected-device-types/building-the-service-manager.rst
ref-docs/hubaction-ref.rst
ref-docs/reference.rst
ref-docs/smartapp-ref.rst

This is a document for HubAction API reference. The "hubaction-ref.rst" is the main document. 
@lbredeso @jimmyjames please review
/cc @bflorian @jodyalbritton @workingmonk 
Thanks for all your help!
Raj

[DOCS-422] Documenting HubAction API Reference

---

latest-updates.rst

Minor editorial and link fixes.

[DOCS-445] Fxing "Latest Updates" for January 23, 2017 release

---

latest-updates.rst
ref-docs/device-ref.rst
smartapp-developers-guide/scheduling.rst

Release notes for 08 February docs release.

---

_static/css/custom.css
capabilities-reference.rst
conf.py
index.rst

Updates the docs homepage with a card-based grid layout to bring attention to specific areas of interest for the docs. Uses simple responsive HTML/CSS and FontAwesome (included by RTD theme) for icons.

[DOCS-425] - more user-friendly docs homepage

---

index.rst
latest-updates.rst

@rajkaramchedu please review - looking to get the homepage improvements out live this week.

docs release for 10 Feb 2017

---

ref-docs/device-handler-ref.rst
ref-docs/smartapp-ref.rst
smartapp-developers-guide/scheduling.rst

DOCS-452 Add runEvery1Minute to Device/SmartApp Scheduling API

---

contributing/index.rst
contributing/style-guide.rst
index.rst

[DOCS-458] Style guide for titles

---

getting-started/first-smartapp.rst
getting-started/getting-help.rst
getting-started/groovy-basics.rst
getting-started/groovy-for-smartthings.rst
getting-started/overview.rst
getting-started/up-and-running.rst

All six guides in Getting Started section are revised for title and section heading style fixes. 
@jimmyjames please check, thanks!

[DOCS-458] Title and section heading style fixes for Getting Started

---

arduino/index.rst
code-review-guidelines.rst

Only title and section headings style updates for the below docs:
1) Arduino ThingShield
2) Code Review Guidelines
@jimmyjames Please review, thanks!

[DOCS-458] Style updates for titles and section headings

---

latest-updates.rst
smartapp-developers-guide/parent-child-smartapps.rst

Release notes for 02 march 2017 docs release

---

contributing/style-guide.rst

[DOCS-461] UI element style update

---

device-type-developers-guide/building-zigbee-device-handlers.rst
device-type-developers-guide/quick-start.rst
device-type-developers-guide/simulator-metadata.rst
device-type-developers-guide/tiles-metadata.rst
getting-started/first-smartapp.rst
smartapp-developers-guide/preferences-and-settings.rst
smartapp-web-services-developers-guide/overview.rst
smartapp-web-services-developers-guide/smartapp.rst
smartapp-web-services-developers-guide/tutorial-part1.rst
smartapp-web-services-developers-guide/tutorial-part2.rst
tools-and-ide/account-mgmt.rst
tools-and-ide/github-integration.rst
tools-and-ide/logging.rst

@jimmyjames please check. Covers all docs.

[DOCS-461] UI elements style updated

---

contributing/style-guide.rst

[DOCS-462] Adding list style guide section

---

contributing/style-guide.rst

[DOCS-464] style guide for api docs

---

publishing/index.rst

@tslagle13 @dbradmit please review.

[DOCS-460] update publication for public distribution docs

---

ref-docs/device-ref.rst

fix statesSince example

---

cloud-and-lan-connected-device-types-developers-guide/autodiscover-lan.rst
cloud-and-lan-connected-device-types-developers-guide/index.rst

@jimmyjames @workingmonk Note that this is same as #545. Fresh branch to kill the merge conflicts there. Review this, and not #545. Thanks!

[DOCS-431] Documenting Super LAN Connect App

---

latest-updates.rst

release notes for 08 march 2017

---

cloud-and-lan-connected-device-types-developers-guide/building-cloud-connected-device-types/building-the-service-manager.rst
cloud-and-lan-connected-device-types-developers-guide/building-lan-connected-device-types/building-the-service-manager.rst
code-review-guidelines.rst
device-type-developers-guide/definition-metadata.rst
device-type-developers-guide/device-integration.rst
device-type-developers-guide/overview.rst
device-type-developers-guide/parse.rst
device-type-developers-guide/tiles-metadata.rst
device-type-developers-guide/z-wave-primer.rst
device-type-developers-guide/zigbee-primer.rst
getting-started/getting-help.rst
latest-updates.rst
smartapp-developers-guide/anatomy-and-life-cycle-of-a-smartapp.rst
smartapp-developers-guide/parent-child-smartapps.rst
smartapp-developers-guide/preferences-and-settings.rst
smartapp-developers-guide/scheduling.rst
smartapp-developers-guide/state.rst
smartapp-web-services-developers-guide/authorization.rst
smartapp-web-services-developers-guide/overview.rst
smartapp-web-services-developers-guide/tutorial-part1.rst
tools-and-ide/editor-and-simulator.rst
tools-and-ide/logging.rst

Including a few other edits.
@jimmyjames

[DOCS-462] Revised list styling

---

contributing/style-guide.rst

@jimmyjames please check, thanks.

[DOCS-463] Glossary of SmartThings terms

---

capabilities-reference.rst

Documenting the BOOLEAN data type

added boolean data type description

---

smartapp-web-services-developers-guide/tutorial-part1.rst

Target master for typo fix in #635

target master for small typo fix in #635

---

readthedocs/settings/local_settings.py

trying local_settings as per rtd docs

try adding local settings

---

capabilities-reference.rst

[DEVP-285] add warning that capabilities docs here no longer maintained

---

getting-started/up-and-running.rst

With Account Migration live and the register URL hidden in Prod, figured we'd want to change this.

Edited the Account creation URL

---

_theme/sphinx_rtd_theme/layout.html

Update banner to have new link to distribution for both CST and WWST.

fix broken distribution link
