SmartThingsCommunity/Documentation

- smartapp-developers-guide/scheduling.rst
reorganize a bit, add some more info around date string formats, and add info about discouraging using runIn to create schedules for less than sixty seconds.
> scheduling doc updates

- smartapp-developers-guide/scheduling.rst
@mrnohr does it make sense to document the unschedule performance limitations for now? Take a look, thanks
> unschedule is expensive. can't fix it quickly, so document it for now.

- reference-material.rst
I always have to go to the z-wave primer to find this link (we don't need no stinkin' bookmarks!) and it's a reference that is also written/maintained/hosted by ST, so it seemed sensible to link to it from the reference materials page.
> Added link to zwave util ref to references pg

- device-type-developers-guide/building-zigbee-device-handlers.rst
adding a note that describes how 1400 payload translates to 2 seconds in the "write" section of the zigbee device handler guide.
> adding clarification on zigbee device handler doc

- smartapp-web-services-developers-guide/tutorial-part1.rst
There is a typo error on "smartapp-web-services-developers-guide/tutorial-part1.html" page when I have gone through the documentation. http://screencast.com/t/QxCOXjOSe1L
> Fixed typo error on "smartapp-web-services-developers-guide/tutorial-part1.html" page

- ref-docs/smartapp-ref.rst
Attempt to differentiate contentType as forced response type and requestContentType as actual request type.
> Update contentType docs and fix typos

- device-type-developers-guide/building-zigbee-device-handlers.rst
- device-type-developers-guide/zigbee-primer.rst
- smartapp-developers-guide/preferences-and-settings.rst
@tpmanley Here is the updated example. Let me know if this looks correct to you.
> updating incorrect example for zigbee wattr method.

- tools-and-ide/github-integration.rst
Should be `git push <remote> <branch>`, not `git push <remote>/<branch>`.
> fix type for pushing to master.

- device-type-developers-guide/tiles-metadata.rst
A community member was (understandably!) confused that string interpolations in the tiles method use single quotes, and fails with double quotes. This is not as Groovy's string interpolation is defined (only works with double quotes), so causes confusion.
I added a clarifying tip near this code example that was causing confusion. What we really need is an entire lifecycle diagram/overview as discussed previously, but given the current docs backlog I don't want this clarification to go undocumented until such time as we find bandwidth/priority for the lifecycle diagram.
@mrnohr would be good for you to review/comment/suggest.
> only single quotes can be used to interpolate string vals in the tiles definition

- smartapp-developers-guide/preferences-and-settings.rst
This is currently only available in iOS (and doc'd as such); ticket created for support across other OS's.
> add docs for using capitalization options on input element. 

- ref-docs/device-handler-ref.rst
- ref-docs/event-ref.rst
- ref-docs/smartapp-ref.rst
It's come up a few times in the forums and elsewhere about how to pass/get additional information on an event. Events support a `data` option to allow passing a map of additional information. Add this to the reference docs.
This will also be a good example of another type of "recipe" that could be added to a cookbook-style section in the docs (future project)
> add information about passing/getting data on events

- smartapp-developers-guide/routines.rst
When a routine is executed, a location event is created. This enables SmartApps to subscribe to a `"routineExecuted"` event in their SmartApp.
> add docs around routine events

- cloud-and-lan-connected-device-types-developers-guide/building-lan-connected-device-types/building-the-service-manager.rst
mDNS/Bonjour device discovery has not been fully integrated and tested at this time. Remove this section from the docs until it is fully tested/supported, so as to avoid confusion.
> remove docs for device discovery via Bonjour

- smartapp-developers-guide/parent-child-smartapps.rst
Clarify that when trying to save a SmartApp that has the `parent` option in the definition (because it's a child SmartApp), the platform will attempt to find a SmartApp with the given namespace/name. If one is not found, an error will occur.
There's a whole section that will need to be updated around the install lifecycle for parent/child SmartApps as well (so that we know when each install()/updated() is called, when parent/child references are available), etc.
> Clarify that child SmartApps will validate parent on save.

- device-type-developers-guide/building-z-wave-device-handlers.rst
It doesn't appear to work to return only a HubAction from parse(), it only processes hub actions that are returned as part of a list. Returning [event, response(cmds)] is the current best practice for this kind of handler.
> Fix broken Z-Wave response() example

- smartapp-developers-guide/preferences-and-settings.rst
Correct cacapability to capability in "input" section, "type" table
> Correct typo in "input" section

- ref-docs/smartapp-ref.rst
- smartapp-web-services-developers-guide/authorization.rst
- smartapp-web-services-developers-guide/index.rst
- smartapp-web-services-developers-guide/overview.rst
- smartapp-web-services-developers-guide/rate-limiting.rst
- smartapp-web-services-developers-guide/smartapp.rst
- smartapp-web-services-developers-guide/tutorial-part1.rst
- smartapp-web-services-developers-guide/tutorial-part2.rst
Goals of this PR:
* Update documentation steps for the OAuth authorization flow to use the `uri` to receive the server-specific SmartApp endpoint.
* Add documentation for the web services SmartApp, including how to expose endpoints, work with the request, response, and errors.
* Update the organization of the web services documentation so that it's easier to navigate and find relevant info.
TODO - add documentation for the removal of the ability to install self-published SmartApps.
Example source code referenced in this documentation is found in this PR: https://github.com/SmartThingsCommunity/Code/pull/13
/cc @tslagle13 @unixbeast
> Update web services

- smartapp-developers-guide/anatomy-and-life-cycle-of-a-smartapp.rst
This keeps coming up, and for good reason. It's not documented currently what the execution timeout limits are.
Longer-term, I really want to document the sandboxed execution environment in more detail. This is really a stop-gap commit to at least have *something* there, until such time that we can budget the resources/priority to document it better.
> add basic docs on sandbox timeouts.

- smartapp-developers-guide/sending-notifications.rst
While contact book is not available for end users yet, developers should still use the contact book APIs (with the fall-back mechanism documented) to ensure their SmartApp is future-proofed.
> clarify that contact book is not an end-user available feature yet.

- ref-docs/device-handler-ref.rst
> Fixed typo: "JSON-encoded body"

- capabilities-reference.rst
Adding garage door control capability. There is no technical difference between door control and garage door control.
The specific use case for one over the other is to have the ability to only choose device with the specific capability. i.e. If you have a garage door smartapp, you probably only want to be able to choose devices that implement the garage door capability instead of getting a list of all doors.
> adding garage door control capability

- getting-started/overview.rst
It appears like a minor error in wording snuck itself into the doc, as SmartThings probably ship with SmartApps, not with SmartThings.
> Fixed minor wording mistake

- capabilities-reference.rst
The Momentary capability probably should define its own attribute so that it can become better standardized.
Until then, clarify that it does not have any attributes, so won't have any standard events.
> add note to clarify Momentary capability

- smartapp-web-services-developers-guide/smartapp.rst
A ticket has been created to change this behavior so a request handler can send back a custom response. But until that is done, document the current behavior.
> clarify that PUT request handlers return 204 and cannot be changed

- smartapp-developers-guide/preferences-and-settings.rst
In the page2() dynamicPage, the setting "action" was being used twice and over written.
> Action was being overwritten by overloaded usage

- device-type-developers-guide/tiles-metadata.rst
This is to reflect new functionality introduced in version 2.1.0 of our Android and iOS apps.
> Adding note on new VALUE_CONTROL functionality for multi-attribute tiles

- capabilities-reference.rst
This corrects the input type from "enum" to "string"
Closes #247
> Correct the parameter input type for setThermostatX commands

- smartapp-developers-guide/preferences-and-settings.rst
The entire preferences page needs an overhaul, reorg, and more content.
This PR is not that - just a quick change to clarify how to access preference inputs in a SmartApp with an example.
> quick clarification on accessing preferences inputs.

- device-type-developers-guide/tiles-metadata.rst
Passing a list of tiles to `main()` is no longer useful, since the user cannot choose their main tile. Removing it from the docs to avoid confusion.
> using main tile with a list is useless now

- README.md
- requirements.txt
I followed previous instructions to build the documentation locally, but it doesn't cover installation of dependencies (except Sphinx).
e.g.
```
$ make html
sphinx-build -b html -d _build/doctrees   . _build/html
Traceback (most recent call last):
File "/usr/bin/sphinx-build", line 5, in <module>
from pkg_resources import load_entry_point
File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 2655, in <module>
working_set.require(__requires__)
File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 648, in require
needed = self.resolve(parse_requirements(requirements))
File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 546, in resolve
raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: docutils>=0.4
make: *** [html] Error 1
```
So I changed …
> adding instructions for installing deps using pip/virtualenv

- contributing/index.rst
- contributing/style-guide.rst
- index.rst
This PR adds some basic information for contributing to the docs, including document page structure and common sphinx-related formatting/conventions.
@unixbeast please review to ensure we are aligned on the standards specified in this PR.
Once this is merged, we can make some commits to address inconsistencies to these standards in our current documentation.
> add info for contributing to the docs

- getting-started/first-smartapp.rst
- getting-started/groovy-basics.rst
- getting-started/up-and-running.rst
- sept-2015-faq.rst
This gets us down to 1 pesky warning about the favicon not existing; it is being picked up, so it's not clear to me yet how to avoid the build warning but still get the favicon.
@unixbeast 
I think we can address these warnings and spend a little time later to see if we can get rid of the one remaining warning. Would be great to get a totally clean build.
> fix build warnings

- cloud-and-lan-connected-device-types-developers-guide/building-lan-connected-device-types/building-the-service-manager.rst
- cloud-and-lan-connected-device-types-developers-guide/building-lan-connected-device-types/src/generic-upnp-device.groovy
- cloud-and-lan-connected-device-types-developers-guide/building-lan-connected-device-types/src/generic-upnp-service-manager.groovy
There's a lot of changes in here. Here's a summary at a high level:
1. Promote use of new ssdpTerm location event subscriptions
2. Show limited example of HubAction callbacks
3. Include better information on UPnP, especially linking to the actual specification, not Wikipedia articles (I like Wikipedia, don't get me wrong, but it has dramatically less information in this case)
4. Include Generic UPnP Service Manager and Device examples, for illustrative purposes (they also actually work)
CC-ing folks who have asked me about this work, hope I haven't forgotten anyone.
/cc @unixbeast @jimmyjames @larsfinander @juano2310 @Yaima @CCarden @tslagle13
> SHARD-103: Rewrite of Service Manager documentation

- smartapp-web-services-developers-guide/smartapp.rst
- smartapp-web-services-developers-guide/tutorial-part1.rst
I think at some point in the near future some of this needs to be moved to, and expanded on, in a dedicated best practices section or page. For now we want to get this out there soon so it's not leading people down a wrong path, and provides some clarity on not allowing arbitrary command execution through endpoint mappings.
@danlieberman @unixbeast
> DOCS-277 - do not allow arbitrary command execution through an endpoint

- getting-started/first-smartapp.rst
- tools-and-ide/editor-and-simulator.rst
- tools-and-ide/logging.rst
@jodyalbritton this removes references to the logging console from the docs as discussed.
> DOCS-281 - remove logging console from docs

- smartapp-developers-guide/preferences-and-settings.rst
The word "default" in the description description can cause confusion leading the developer believe that it works similar to defaultValue which (in hind sight) is not the case.
> Remove "default" from the description

- tools-and-ide/cli.rst
This is still a WIP but this PR contains a few formatting changes:
* Add introductory text to clearly state what the CLI can do for developers
* Streamline download and install instructions by OS
* Move scenarios above commands
* Breakout create, save, publish into separate sub-topics
@unixbeast
> formatting fixes/suggestions for cli docs

- ref-docs/zigbee-ref.rst
This resolves https://smartthings.atlassian.net/browse/DOCS-298
@tpmanley
> Add additionalParams documentation for zigbee library

- device-type-developers-guide/device-preferences.rst
Finally adding some basic device handler preference docs. This can evolve if/when device handler preferences are brought to par with SmartApp preferences.
@vlaminck would appreciate your review for accuracy
> [DOCS-75] add device preferences docs

- code-review-guidelines.rst
- smartapp-developers-guide/state.rst
Using collections in atomicState has caused confusion for developers when trying to modify the collection (adding, changing, or removing elements). The behavior is different between `state` and `atomicState`, creating more confusion.
This PR attempts to document the differences and a recommended way of working with collections in `atomicState`. 
I do not know if this behavior is intentional, a bug, or an unintended consequence of the implementation of `atomicState`. This PR simply documents how things behave right now.
@rappleg or @Bijnagte I'd like you to review/confirm this, or delegate to someone who can review.
/cc @dsainteclaire
> [DOCS-304] added documentation around using collections in state

- docs-change-log.rst
- index.rst
- sept-2015-faq.rst
Also moves the docs change log up to the top of the nav tree.
/cc @tslagle13
> [DOCS-319] remove sept 2015 release faq from top nav

- device-type-developers-guide/index.rst
- device-type-developers-guide/other-available-apis.rst
- smartapp-developers-guide/calling-web-services-in-smartapps.rst
- smartapp-developers-guide/state.rst
Device Handlers can call scheduling, state, and http APIs (for the most part, with exceptions noted in the changes in this PR). Our current docs organization makes discovering these APIs within Device Handler development less than optimal. Rather than duplicate the content within the DH guide, or not do anything until the entire organization/information hierarchy is redone, I just created a new page with links to topics in the SmartApp guide.
I also changed a couple titles of docs to make them more clear/discoverable.
> [DOCS-254] - add links in the Device Handler guide to other available APIs

- ref-docs/smartapp-ref.rst
I wanted to resolve #386  that I submitted just a few minutes ago. 
It's a trivial fix that I've checked in the simulator.
> correct missing brace in httpget example 

- capabilities-reference.rst
@unixbeast not sure when this was removed but this is the sort of manual updates we won't have to make soon hopefully!
> occupancy capability was removed when capability definitions moved

- capabilities-reference.rst
Taking out hex, switch, and level from the supported color map options. These are not inherently supported by the capability, however, some device handlers may implement support for these values.
> correcting color-control capability

- ref-docs/smartapp-ref.rst
- smartapp-developers-guide/scheduling.rst
Just expands on and incorporates recent state changes (for the JSON serialization stuff) into the changes started with https://github.com/SmartThingsCommunity/Documentation/pull/382.
Requires data-management PR #3105 to be deployed before merging/deploying.
> [DOCS-159] - passing data to scheduled method handlers

- device-type-developers-guide/overview.rst
- device-type-developers-guide/parse.rst
- device-type-developers-guide/zigbee-example.rst
This commit fixes a few references to "ZibBee" which is not
a thing.  ZigBee is, however, and clearly the intent of the
author.
> typo: device types: ZibBee -> ZigBee

- ref-docs/app-state-ref.rst
- ref-docs/attribute-ref.rst
- ref-docs/capability-ref.rst
- ref-docs/command-ref.rst
- ref-docs/device-handler-ref.rst
- ref-docs/device-ref.rst
- ref-docs/event-ref.rst
- ref-docs/hub-ref.rst
- ref-docs/installed-smart-app-wrapper-ref.rst
- ref-docs/location-ref.rst
- ref-docs/mode-ref.rst
- ref-docs/reference.rst
- ref-docs/smartapp-ref.rst
- ref-docs/state-ref.rst
In anticipation of the updated `getChildApps()` method, it increasingly seems confusing that we document our getters using the Groovy property syntax shortcut. Presenting them as properties also causes confusion because it can lead developers to think that they can set the values as well (which they can't). 
@unixbeast you should review this please.
/cc @rajkaramchedu as you look at the Time story if you make updates to the reference docs you'll want to get this change (once merged) and follow the same pattern.
> [DOCS-344] - refactor reference API docs to use getter style

- ref-docs/smartapp-ref.rst
Added the reference for nextOccurrence() time-method. At the moment the source is the method definition and implementation in https://smartthings.atlassian.net/secure/attachment/38376/CoreApi.txt and an example code that validates the implementation. However, I haven't worked on discovering any gotchas or ins-and-outs we need to watch for, yet.
> [DOCS-9] Added nextOccurrence() reference

- ref-docs/installed-smart-app-wrapper-ref.rst
- ref-docs/smartapp-ref.rst
Document the following methods, including which return complete and incomplete installations, versus those that only return complete installs:
* `getAllChildApps()` (on SmartApp)
* `findAllChildAppsByName()` (on InstalledSmartAppWrapper)
* `findAllChildAppsByNamespaceAndName()` (on InstalledSmartAppWrapper)
* `findChildAppByNamespaceAndName()` (on InstalledSmartAppWrapper)
* `getAllChildApps()` (on InstalledSmartAppWrapper)
Also clarify that `getChildApps()` will now only return complete child SmartApp installs.
@chrisfsmith please review, thanks!
> [DOCS-344] - add docs for getAllChildApps() methods and their derivatives

- ref-docs/device-handler-ref.rst
- ref-docs/smartapp-ref.rst
This gets the scheduling reference docs consistent across SmartApps and Device Handlers, and adds in the signatures for passing a data map to scheduled handler methods.
> [DOCS-366] fix up scheduling reference docs

- ref-docs/smartapp-ref.rst
Related to [DOCS-9] JIRA, but not directly. Just spotted this error in the timeZone() API reference and fixed it.
> [DOCS-9] Corrected timeZone() method description

- _static/custom.css
- conf.py
- index.rst
Some minor styling improvements:
- nav search area color gradient to be consistent with developers.smartthings.com
- more prominent font size and color for the captions in the nav tree
- consistent font for search text
I also reorganized the toc just a little to tighten things up in the nav tree.
Since overriding styles like this isn't ideal, I've created DOCS-397 to create our own sphinx theme (can just be a fork of the current RTD theme with our modifications to start).
> [DOCS-396] styles consistent with developer.smartthings.com

- device-type-developers-guide/definition-metadata.rst
- ref-docs/device-ref.rst
@workingmonk please review
In `device-ref.rst` there are some organizational changes that don't change content. The only change to look at there is the documentation for `getManufacturerName()` and `getModelName()`.
> [DOCS-361] document manufacturer and model name on device

- tools-and-ide/editor-and-simulator.rst
Moved the note from bottom of simulator section to the top and changed it to warning.
> [DOCS-398] Added warning in Simulator section

- arduino/index.rst
Use double backslash on Windows path for proper escaping
> Fix Windows backslashes

- conf.py
- test.rst
-fix the weird spacing for color control and music player attributes in jinja template (this was the SmartThingCapabilities repo fix)
-get rid of tailing ',' character in params list for commands.
-Get rid of unnecessary table columns
-Alphabetize the table
> DOCS-415 correcting some issues with template

- device-type-developers-guide/zigbee-primer.rst
- ref-docs/zigbee-ref.rst
This adds documentation for the ZCL message class that can be used for
generating ZCL Zigbee messages for communicating with devices through
the hub.  This abstracts the different methods of messages between v1
and non-v1 hubs.
@unixbeast  Tom and I discussed the possibility of re-organizing some of this stuff.  I think in general the `zigbee.XXX` methods we want to be static backwards compatible calls.  However, the information about the ZCL classes, while it is available and does allow a few very edge case things that aren't supported by the `zigbee` methods, in general we aren't sure we won't make some changes to the interface in the future.  Would it make sense to re-organize and have those in a different location for more specific documentation that is "use with the understanding …
> [DOCS-331] Add documentation for ZCL message classes

- tools-and-ide/github-integration.rst
A 3rd party developer asked the question if the directory names need to be in lowercase for the GitHub integration to work. See here: https://github.com/SmartThingsCommunity/Documentation/issues/514
The answer is yes and this PR is to add the clarification to the docs.
> [DOCS-418] Add a note on lowercase directory names

- capabilities-reference.rst
Some minor UX changes to the template:
- Removed the trailing `:` from "Attributes" and "Commands" section headers, since section headers by convention do not have a trailing colon.
- Removed bold styling from "Attributes" and "Commands" since it is already a section header.
- Made "Preferences Reference" its own section for each capability, so it appears in the side navigation along with Attributes and Commands, and looks consistent with them.
- Removed trailing colon from the command name, since the indentation for the definition is enough to notify the reader that the definition follows.
Before:
With Changes:
I'm open to discussing these changes if people don't like them. @unixbeast also please review in case there is some negative impact with modifying the template as I have that I'm …
> some minor visual changes to capabilities reference template

- getting-started/first-smartapp.rst
The author probably meant 'discrete' instead of 'discreet', but even that is redundant with 'possible values'.
> Fix grammatical error

- smartapp-developers-guide/devices.rst
address issue raised in #501 but uses the `:ref:` target instead of relying on html target
> fix broken links

- ref-docs/smartapp-ref.rst
Initial draft of sendHubCommand() method documentation. This will go in API reference doc. 
@workingmonk please review. If you can add any more detail, in specific an example code fragment for sending a List of HubAction commands, it'll be very helpful. Thanks!
> [DOCS-419] Adding sendHubCommand() doc

- ref-docs/event-ref.rst
I think it's really rather that the implementation is broken and
the function is supposed to return a Map, but right now it returns a
String, at least for the "DeviceUpdated" event.
Either way, the documentation of the Signature vs Returns is definitely
inconsistent.
> fix Event::getData() documentation

- tools-and-ide/github-integration.rst
This PR just adds a warning that enabling GitHub may cause performance issues. At least hopefully then users can make the choice if the convenience is worth the potential performance impact.
/cc @rajkaramchedu
> [DOCS-434] add warning that github may slow IDE

- README.md
- ref-docs/device-ref.rst
These methods are currently undocumented - adding docs:
getLastActivity returns the date of the last event with a source of 'Device'
getStatus returns the status of the device - i.e. ONLINE, ACTIVE, INACTIVE.. if the device doesn't have a status then INACTIVE will be returned.
> [DOCS-446] Add getLastActivityDate and getStatus to Device

- smartapp-developers-guide/scheduling.rst
@rappleg this just rearranges some content and adds some more emphasis to prefer `runEvery` over cron when possible.
/cc @rajkaramchedu
> [DOCS-450] - emphasize using runEvery* instead of cron.

- _static/css/custom.css
- _static/javascript/copycode.js
Use a copy button instead of an icon with tooltips. 
Allows us to remove a bunch of tooltip CSS and the UX is more streamlined as a result.
Before:
After:
> Use button instead of tooltip for copy code

- architecture/index.rst
- publishing/index.rst
- ratelimits/index.rst
Updated styles for titles and section headings only for three guides: 
1) Architecture, 
2) Rate Limits and 
3) Publishing Code.
@jimmyjames Please check. Also I went with "cloud" instead of "Cloud," and "Web services" instead of "Web Services," as a trial before we decide which way to standardize.
> [DOCS-458] Style updates for titles and section headings only

- capabilities-reference.rst
- ref-docs/async-http-ref.rst
- ref-docs/async-response-ref.rst
- ref-docs/reference.rst
- ref-docs/zigbee-ref.rst
Only title and section headings style updates for the below docs:
1) Capabilities Ref
2) API Doc
@jimmyjames Please review, thanks! This completes titles and section headings scrub.
> [DOCS-458] Style updates for titles and section headings

- _static/capabilities/bridge.src/bridge.properties
- _static/capabilities/bridge.src/bridge.xml
- _static/capabilities/button.src/button.properties
- _static/capabilities/button.src/button.xml
Note that the actual bridge properties file in the Capabilities repo is wrong; this PR has a manually edited version to get the docs rendering to work. PR to fix the actual properties file is in the capabilities repo (PR 73)
> button capability updated; bridge capability added.

- capabilities-reference.rst
- requirements.txt
Until all capabilities are properly mapped to new SmartThings mobile app, put all capabilities reference back in legacy docs site.
Note that these docs used to be auto-generated, but that has been removed since it wasn't used and also  relied on capabilities being in XML format (they are now YAML), and docstrings in properties files (now yaml i18n files). Also just dumping the yaml definition as the docs here, since this is a temporary solution.
> [DOCS-517] put back some basic capabilities docs in legacy site

- _static/css/sphinx_override.css
Fixing regression with nav links above a viewport width of 768px. The entire `<ul>` was being displaced off-screen when the parent div was in the `:active` state.
> Fix unclickable nav links

- _theme/sphinx_rtd_theme/theme.conf
- conf.py
According to notable issues such as [sphinx-doc/sphinx #2090](https://github.com/sphinx-doc/sphinx/issues/2090), there's an issue with the appropriate files not being copied from `_static` into the `_build/html` directory. Evidently this is not a problem with a regular ol' ReadTheDocs build because it seems to do something other than `make html`. 
In `conf.py`, add the line `html_static_path = ['_static']`, which was previously commented out and had no value at all. 
When using `make html`, the output seemed to include a reference to `css/theme.css`, which was configured in `sphinx_rtd_theme/theme.conf`, but it was never actually used in the actual RTD site (take a look in dev tools [here](https://docs.smartthings.com/en/latest/), `theme.css` is never requested). Since we were entirely …
> Fix output of "make html"
